name: Validate code on Pull request

on:
  pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node env
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 16

      - name: Install dependencies
        run: yarn

      - name: Lint
        run: yarn lint


